package ch.so.agi.datahub.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import ch.so.agi.datahub.cayenne.CoreOrganisation;
import ch.so.agi.datahub.cayenne.CoreTheme;

/**
 * Class _CoreOperat was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CoreOperat extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String T_ID_PK_COLUMN = "t_id";

    public static final StringProperty<String> ANAME = PropertyFactory.createString("aname", String.class);
    public static final EntityProperty<CoreOrganisation> CORE_ORGANISATION = PropertyFactory.createEntity("coreOrganisation", CoreOrganisation.class);
    public static final EntityProperty<CoreTheme> CORE_THEME = PropertyFactory.createEntity("coreTheme", CoreTheme.class);

    protected String aname;

    protected Object coreOrganisation;
    protected Object coreTheme;

    public void setAname(String aname) {
        beforePropertyWrite("aname", this.aname, aname);
        this.aname = aname;
    }

    public String getAname() {
        beforePropertyRead("aname");
        return this.aname;
    }

    public void setCoreOrganisation(CoreOrganisation coreOrganisation) {
        setToOneTarget("coreOrganisation", coreOrganisation, true);
    }

    public CoreOrganisation getCoreOrganisation() {
        return (CoreOrganisation)readProperty("coreOrganisation");
    }

    public void setCoreTheme(CoreTheme coreTheme) {
        setToOneTarget("coreTheme", coreTheme, true);
    }

    public CoreTheme getCoreTheme() {
        return (CoreTheme)readProperty("coreTheme");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "aname":
                return this.aname;
            case "coreOrganisation":
                return this.coreOrganisation;
            case "coreTheme":
                return this.coreTheme;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "aname":
                this.aname = (String)val;
                break;
            case "coreOrganisation":
                this.coreOrganisation = val;
                break;
            case "coreTheme":
                this.coreTheme = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.aname);
        out.writeObject(this.coreOrganisation);
        out.writeObject(this.coreTheme);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.aname = (String)in.readObject();
        this.coreOrganisation = in.readObject();
        this.coreTheme = in.readObject();
    }

}
