package ch.so.agi.datahub.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import ch.so.agi.datahub.cayenne.CoreOperat;

/**
 * Class _CoreTheme was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CoreTheme extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String T_ID_PK_COLUMN = "t_id";

    public static final StringProperty<String> ANAME = PropertyFactory.createString("aname", String.class);
    public static final StringProperty<String> CONFIG = PropertyFactory.createString("config", String.class);
    public static final StringProperty<String> METACONFIG = PropertyFactory.createString("metaconfig", String.class);
    public static final ListProperty<CoreOperat> CORE_OPERATS = PropertyFactory.createList("coreOperats", CoreOperat.class);

    protected String aname;
    protected String config;
    protected String metaconfig;

    protected Object coreOperats;

    public void setAname(String aname) {
        beforePropertyWrite("aname", this.aname, aname);
        this.aname = aname;
    }

    public String getAname() {
        beforePropertyRead("aname");
        return this.aname;
    }

    public void setConfig(String config) {
        beforePropertyWrite("config", this.config, config);
        this.config = config;
    }

    public String getConfig() {
        beforePropertyRead("config");
        return this.config;
    }

    public void setMetaconfig(String metaconfig) {
        beforePropertyWrite("metaconfig", this.metaconfig, metaconfig);
        this.metaconfig = metaconfig;
    }

    public String getMetaconfig() {
        beforePropertyRead("metaconfig");
        return this.metaconfig;
    }

    public void addToCoreOperats(CoreOperat obj) {
        addToManyTarget("coreOperats", obj, true);
    }

    public void removeFromCoreOperats(CoreOperat obj) {
        removeToManyTarget("coreOperats", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<CoreOperat> getCoreOperats() {
        return (List<CoreOperat>)readProperty("coreOperats");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "aname":
                return this.aname;
            case "config":
                return this.config;
            case "metaconfig":
                return this.metaconfig;
            case "coreOperats":
                return this.coreOperats;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "aname":
                this.aname = (String)val;
                break;
            case "config":
                this.config = (String)val;
                break;
            case "metaconfig":
                this.metaconfig = (String)val;
                break;
            case "coreOperats":
                this.coreOperats = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.aname);
        out.writeObject(this.config);
        out.writeObject(this.metaconfig);
        out.writeObject(this.coreOperats);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.aname = (String)in.readObject();
        this.config = (String)in.readObject();
        this.metaconfig = (String)in.readObject();
        this.coreOperats = in.readObject();
    }

}
